name: ITH_AEM_Project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - ipywidgets
  - simpeg
  - discretize
  - dill
  - pytest
  - pip
  - pip:
      - multiprocess  # fallback for multiprocessing in some environments
